// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	MovieCreate(ctx context.Context, in *MovieCreateRequest, opts ...grpc.CallOption) (*MovieCreateResponse, error)
	MovieList(ctx context.Context, in *MovieListRequest, opts ...grpc.CallOption) (*MovieListResponse, error)
	MovieUpdate(ctx context.Context, in *MovieUpdateRequest, opts ...grpc.CallOption) (*MovieUpdateResponse, error)
	MovieDelete(ctx context.Context, in *MovieDeleteRequest, opts ...grpc.CallOption) (*MovieDeleteResponse, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) MovieCreate(ctx context.Context, in *MovieCreateRequest, opts ...grpc.CallOption) (*MovieCreateResponse, error) {
	out := new(MovieCreateResponse)
	err := c.cc.Invoke(ctx, "/ozon.dev.homework.api.Admin/MovieCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) MovieList(ctx context.Context, in *MovieListRequest, opts ...grpc.CallOption) (*MovieListResponse, error) {
	out := new(MovieListResponse)
	err := c.cc.Invoke(ctx, "/ozon.dev.homework.api.Admin/MovieList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) MovieUpdate(ctx context.Context, in *MovieUpdateRequest, opts ...grpc.CallOption) (*MovieUpdateResponse, error) {
	out := new(MovieUpdateResponse)
	err := c.cc.Invoke(ctx, "/ozon.dev.homework.api.Admin/MovieUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) MovieDelete(ctx context.Context, in *MovieDeleteRequest, opts ...grpc.CallOption) (*MovieDeleteResponse, error) {
	out := new(MovieDeleteResponse)
	err := c.cc.Invoke(ctx, "/ozon.dev.homework.api.Admin/MovieDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility
type AdminServer interface {
	MovieCreate(context.Context, *MovieCreateRequest) (*MovieCreateResponse, error)
	MovieList(context.Context, *MovieListRequest) (*MovieListResponse, error)
	MovieUpdate(context.Context, *MovieUpdateRequest) (*MovieUpdateResponse, error)
	MovieDelete(context.Context, *MovieDeleteRequest) (*MovieDeleteResponse, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (UnimplementedAdminServer) MovieCreate(context.Context, *MovieCreateRequest) (*MovieCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MovieCreate not implemented")
}
func (UnimplementedAdminServer) MovieList(context.Context, *MovieListRequest) (*MovieListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MovieList not implemented")
}
func (UnimplementedAdminServer) MovieUpdate(context.Context, *MovieUpdateRequest) (*MovieUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MovieUpdate not implemented")
}
func (UnimplementedAdminServer) MovieDelete(context.Context, *MovieDeleteRequest) (*MovieDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MovieDelete not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_MovieCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).MovieCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozon.dev.homework.api.Admin/MovieCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).MovieCreate(ctx, req.(*MovieCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_MovieList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).MovieList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozon.dev.homework.api.Admin/MovieList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).MovieList(ctx, req.(*MovieListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_MovieUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).MovieUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozon.dev.homework.api.Admin/MovieUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).MovieUpdate(ctx, req.(*MovieUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_MovieDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).MovieDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozon.dev.homework.api.Admin/MovieDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).MovieDelete(ctx, req.(*MovieDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ozon.dev.homework.api.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MovieCreate",
			Handler:    _Admin_MovieCreate_Handler,
		},
		{
			MethodName: "MovieList",
			Handler:    _Admin_MovieList_Handler,
		},
		{
			MethodName: "MovieUpdate",
			Handler:    _Admin_MovieUpdate_Handler,
		},
		{
			MethodName: "MovieDelete",
			Handler:    _Admin_MovieDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
